name: Entrega continua

on:
  workflow_call:

jobs:

  ECS:
    runs-on: ubuntu-latest
    environment: CI
    steps:
    - name: configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.EC2_USERNAME }}
        aws-secret-access-key: ${{ secrets.EC2_SECRET_KEY }}
        aws-region: us-east-1
    
    - name: Obtendo arquivo da tarefa
      run: aws ecs describe-task-definition --task-definition Tarefa_API-GO:5 --query taskDefinition > task-definition.json

    - name: copia do task-definition
      run: cp task-definition.json task-definition.json.old
      
    - name: Definição da tarefa do Amazon ECS
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: Go
        image: stug9000/go_ci:${{github.run_number}}
        environment-variables: |
          HOST=${{ secrets.DB_HOST }}
          USER=${{ secrets.DB_USER }}
          PASSWORD=${{ secrets.DB_PASSWORD }}
          DBNAME=${{ secrets.DB_NAME }}
          DBPORT=${{ secrets.DB_PORT }}
          PORT=8000
          
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: Servico_API-Go
        cluster: API-Go
        wait-for-service-stability: true
       
    - name: Requisição
      continue-on-error: true
      run: sleep 30s ; wget apigo-259582971.us-east-1.elb.amazonaws.com:8000/bruno

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: task-definition.json.old 
        service: Servico_API-Go
        cluster: API-Go
        wait-for-service-stability: true
